import Foundation
import SwiftData

/// A single financial event — an income receipt or an expense payment.
@Model
final class Transaction {

    @Attribute(.unique) var id: UUID
    var name: String?              // Optional property for safe SwiftData lightweight schema migration
    var amount: Double             // Always stored as a positive value
    var type: TransactionType      // .income or .expense
    var date: Date
    var note: String               // Additional review, thoughts, or user memo
    var createdAt: Date

    /// Non-nil when this transaction was auto-generated by a RecurringRule.
    /// Stored as a raw UUID so we don't create a hard relationship that
    /// would cascade-delete history if the rule is removed.
    var recurringRuleID: UUID?

    /// Optional attached receipt or document image data (stored externally to optimize database performance).
    @Attribute(.externalStorage) var receiptImageData: Data?

    // MARK: - Relationships

    /// The ledger this transaction belongs to.
    /// Declared without @Relationship here; the owning side is Ledger.transactions.
    var ledger: Ledger?

    /// The category this transaction is filed under.
    /// Owning side is Category.transactions.
    var category: Category?

    /// The account (e.g. bank account, credit card, cash wallet) this transaction belongs to.
    /// Owning side is Account.transactions.
    var account: Account?

    /// Free-form labels (many-to-many with Tag).
    /// .nullify: removing this transaction does not delete the tags themselves.
    @Relationship(deleteRule: .nullify, inverse: \Tag.transactions)
    var tags: [Tag] = []

    // MARK: - Init

    init(
        name: String?         = nil,
        amount: Double,
        type: TransactionType = .expense,
        date: Date            = .now,
        note: String          = "",
        ledger: Ledger?       = nil,
        category: Category?   = nil,
        account: Account?     = nil,
        tags: [Tag]           = [],
        recurringRuleID: UUID? = nil,
        receiptImageData: Data? = nil
    ) {
        self.id               = UUID()
        self.name             = name
        self.amount           = amount
        self.type             = type
        self.date             = date
        self.note             = note
        self.ledger           = ledger
        self.category         = category
        self.account          = account
        self.tags             = tags
        self.recurringRuleID  = recurringRuleID
        self.receiptImageData = receiptImageData
        self.createdAt        = .now
    }

    // MARK: - Computed Helpers

    /// Resolved name for display: falls back to note or category name if name is empty.
    var displayName: String {
        if let trimmedName = name?.trimmingCharacters(in: .whitespacesAndNewlines), !trimmedName.isEmpty {
            return trimmedName
        }
        let trimmedNote = note.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmedNote.isEmpty {
            return trimmedNote
        }
        return category?.name ?? "Uncategorised"
    }

    /// Positive for income, negative for expense (useful for net calculations).
    var signedAmount: Double {
        type == .expense ? -amount : amount
    }

    var isRecurring: Bool { recurringRuleID != nil }
}
